### ISSUE TITLE
Other stuff to add.

### ISSUE THREAD

**Issue by remembertoremind** [agarrharr/awesome-cli-apps#109]
Okay :) So Github is quite new to me so I'm afraid to mess something up.

You should add Ranger Filemanager 
http://ranger.nongnu.org/

Vim (didnt see it in your list?)
http://www.vim.org/

Latex in vim
https://github.com/lervag/vimtex

Sconsify (spotify cli) However libspotify has just been closed so not sure where this is heading.
https://github.com/fabiofalci/sconsify

**Comment by aharris88** [comment]
Thanks. Welcome to Github.

I should definitely add ranger.

I can't believe I don't have vim or emacs.

You might want to suggest vimtex on this list: https://github.com/akrawchyk/awesome-vim

Let's leave off Sconsify though since libspotify isn't available for download.

Do you want to put in pull requests for any of these? Vim and emacs can be in the same pull request. If not, I can.

**Comment by remembertoremind** [comment]
Thank you :)

Yeah! Ranger is awesome. You should give look at the videos from Luke Smith on youtube:
https://www.youtube.com/watch?v=nlolvAVqn10&t

Yeah its a real bummer with Sconsify but AFAIK they are working on some web api instead which would be awesome.

Sadly I'm a hardcore newb at github so I don't know how to make pull requests :) However I'll be back if i find other cool applications for the terminal.
