### ISSUE TITLE
Check out Command-line Apps on Awesome Node.js

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/awesome-cli-apps#21]
https://github.com/sindresorhus/awesome-nodejs#command-line-apps

**Comment by herrbischoff** [comment]
Since you probably got inspired to add this issue due to my pull request at the Awesome list, I just wanted to let you know that you are of course free to take anything from my list https://github.com/herrbischoff/awesome-command-line-apps. This is all free culture licensed after all. I feel that our lists may have quite different approaches — in scope as well as update frequency. It doesn't matter to me which list gets included in others. I'd even like to contribute, like I extensively did to the awesome-osx repository. I just don't like to be yelled at or moralized by anyone, especially one certain contributor. His posture really repelled me from adding to your project. I honestly see no concurrency here and will appreciate it if your list grows to be useful to many.

**Comment by aharris88** [comment]
Thanks for reaching out. I don't want for there to any hard feelings. I just really like command line apps and I wanted an awesome list.

**Comment by herrbischoff** [comment]
Same here. Let me know if you're open to restructuring, which would open up the possibility of joining the lists. We could possibly even find a way to weigh each list a little differently so both can reasonably exist as complementing each other instead of duplicating certain content. Just a shooting-from-the-hip idea.

**Comment by aharris88** [comment]
Yeah, I'm totally open to restructuring. My list just grew naturally as I discovered cli-apps and my "Other" category just kept growing. If you want to keep separate lists, how do you think we could distinguish our lists from one another?

**Comment by herrbischoff** [comment]
Let me sleep over that idea. Like I said, it was just a quick thought. Maybe one could be more development-focussed and the other more on the general use side. Or we'll simply find out that in the end merging both lists into one humongous one is the best course of action. I'm sure we will figure out how to proceed.

In any case, I feel that your list would benefit from a group-up restructuring, similar to what I'm doing. I have also found that a list like this evolves quite a bit over time, necessitating regrouping entries from time to time.

**Comment by mischah** [comment]
Sorry for Highjacking this issue.

But this seems the right place for a final statement because I feel a bit offended by some worts within this thread:
> I just don't like to be yelled at or moralized by anyone, especially one certain contributor.
> His posture really repelled me from adding to your project.

Mhmm. I think someone got me wrong. 

@herrbischoff
I hope you let me clarify the follwing:
It seems that you feel that I’m have anything against you or your contributions to the »awesome list thing«. That is not the case.

I was a bit disappointed as I saw that your started your list before checking or asking if I would make an an thing out of my idea. But that feeling didn’t last long.

After that I just had to choose on list to contribute to. And I decided the contribute to the list of @aharris88 because he already hat this thing going for a while and it seems like a good base. 
I thought you maybe would realize that too and I would loved to see you participating over here. Because I don’t see the benefit of two lists about the same topic. (Just my point of view. No one is forced to agree.) 

On the other hand your list seems to be on good way too, now. I acknowledge that you put lots of work and love into it the last couple of days.

Back to the topic:
It’s not (and never was) my intention to start an »awesome list war«. I just wanted to contribute to a good thing. And I’m disappointed and that that one person misunderstood my aim and taking something personal which was never meant that way. I’m not quite sure how things evolved into that situation. Maybe I was too enthusiastic to contribute, maybe I’m not that good into writing in english which leads to misinterpreting. Or I was a bit too sarcastic. But the reason isn’t that important. What’s more important that I feel uncomfortable with how things turned out.

So I just have one wish @herrbischoff
Could you please stop offending me personal.
Because I don’t want to deal with this kind of communication online. 

Back to the topic of this issue:
I personally love to idea of merging your lists. No matter under whose username and if you let me contribute (It’s not that I don’t have other things to do).

Thanks for reading :heart:

**Comment by mischah** [comment]
@aharris88 
> Thanks for reaching out. I don't want for there to any hard feelings. I just really like command line apps and I wanted an awesome list.

That’s a good statement :sparkling_heart:

**Comment by mischah** [comment]
@herrbischoff 

After rereading my comments in other threads. I must admit that I have choosen the wrong words and you could also say that I was offending.

I’m sorry for that :pensive:

**Comment by capaldo** [comment]
@jneidel A lot of these apps are already on the list after skimming over them. Wanted to see if its alright to close this as its almost 3+ years old.
