### ISSUE TITLE
Windows CLI Apps?

### ISSUE THREAD

**Issue by StewAlexanderACC** [agarrharr/awesome-cli-apps#333]
Can we as a community provide a few more Windows command line apps to this list, love the list but lets not forget that there is quite a few Windows command line apps out there too.

Not sure if Chocolatey is mentioned anywhere in this list, if it isn't I humbly suggest it should be.

**Comment by StewAlexanderACC** [comment]
Did a search for Chocolatey, nope not in the list ...

It's the missing Windows package manager (there are a few others, but this is by far the most used one in my opinion)

**Comment by jneidel** [comment]
> Not sure if Chocolatey is mentioned anywhere in this list, if it isn't I humbly suggest it should be.

You can open a PR if you want to add an app.

**Comment by jneidel** [comment]
> provide a few more Windows command line apps to this list

I don't think a big part of the community uses Windows, that's why there aren't many Windows specific apps.
I could imagine a Windows specific category ([like for macos](https://github.com/agarrharr/awesome-cli-apps#macos)) if there is interest for that.

I, personally, am against it, as Windows is proprietary bloat and people that use the command-line should know better than to use Windows (or macos for that matter).

If you want to add a category, again, please do so in a PR.

**Comment by StewAlexanderACC** [comment]
I see it's a taste thing ...

Unfortunately Windows is still a HUGE player in the OS market, especially business / government, so although I agree with your opinion of Windows, people still need to get around in it while at work / school.

Say what you will about Macs, but they have popularized a type of BSD (Darwin) much better than say Solaris (and Oracle is getting into the patent troll business, so yeah yuck)

I prefer Debian, but it doesn't have a paid support model - Red Hat is now corporate owned by IBM and let's not talk about the weird Quasimodo that AIX is.

So, yeah I get it, but people still are using Windows, and it would be nice to have a list of CLI software for it.
